### PR TITLE
Upgrade packages and next react

### PR DESCRIPTION
**Pull request by triptec**
## Description

This builds on https://github.com/graphile/starter/pull/295 but fixes the tests and upgrades next and react as well.

## Performance impact

unknown

## Security impact

unknown

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

### CODE REVIEW

**Review by benjie — COMMENTED** [review]
Thanks for the work on this; I'm going to break it up into a series of pull requests and use it as a guide for how to address the various problems that come up.

**Comment by triptec** [comment]
Here's some things I updated in the github actions
```
diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
index e6ad01c..ef21ac6 100644
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -31,14 +31,14 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
       - name: Install pg_dump
         run: |
-          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
           wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
           sudo apt-get update
           sudo apt-get -yqq install postgresql-client-14
@@ -53,7 +53,7 @@ jobs:
       - name: Start worker in background
         run: yarn worker start &
       - name: Cypress run
-        uses: cypress-io/github-action@v2
+        uses: cypress-io/github-action@v5
         with:
           wait-on: http://localhost:5678
           working-directory: "@app/e2e"
diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
index 89b4c49..4dcf95e 100644
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -36,7 +36,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
       - name: Install pg_dump
         run: |
-          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
           wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
           sudo apt-get update
           sudo apt-get -yqq install postgresql-client-14
diff --git a/.github/workflows/production-docker.yml b/.github/workflows/production-docker.yml
index 11ec8a1..4f8c006 100644
--- a/.github/workflows/production-docker.yml
+++ b/.github/workflows/production-docker.yml
@@ -32,7 +32,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
       - name: Install pg_dump
         run: |
-          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
           wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
           sudo apt-get update
           sudo apt-get -yqq install postgresql-client-14
```

**Comment by benjie** [comment]
@triptec If you're interested to raise any of the remaining changes as separate PRs so that we can consider them on their own merits (e.g. one for the docker setup change, one for updating a particular dependency, etc etc) please feel free; but for now I'm going to close this as I think it's effectively been achieved via the following PRs:

- #334
- #335
- #336
- #337
- #338
- #340 
- #341 
- #342 
- 3aa786fe7dd95941e590a9d046fb5fd3c05793da
- #343
- #344

**Comment by triptec** [comment]
Very nice!

**Pull request closed without merging**
