### PR TITLE
Upgrades joaquin

### PR DESCRIPTION
**Pull request by jackbravo**
## Description

Attempts to fix cypress [browser crash.](https://github.com/cypress-io/cypress/issues/350)

Using fix proposed at: https://github.com/cypress-io/github-action/issues/104#issuecomment-666047965

## Checklist

- [ ] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

### CODE REVIEW

**Comment by jackbravo** [comment]
seems to not be running the cypress CI check, so this won't work 😛 .

**Comment by benjie** [comment]
Thanks for keeping chipping away at this @jackbravo. I've no idea what's up or even if it's Cypress' fault or if the issue lies elsewhere and Cypress is paying for it.

**Comment by jackbravo** [comment]
@benjie I feel like I need to install a virtual machine with ubuntu 16.04 to test cypress locally. This flow of testing is very slow :-p. And sadly my work machine today is a mac.

**Comment by benjie** [comment]
I'm running Ubuntu LTS 20.04 and can't reproduce here. I wonder if upgrading `main` branch's Cypress only would have the same issues?

**Comment by jackbravo** [comment]
I know that ubuntu-latest on github-actions means ubuntu 16.04. Maybe we
could try using a newer ubuntu, but cypress is supposed to work on all
versions:
https://github.com/cypress-io/github-action/issues/251

**Comment by mattvb91** [comment]
@jackbravo did you manage to make any progress with the out of memory? I upgraded our actions to Ubuntu 20.04 and still experiencing the same issue

**Comment by jackbravo** [comment]
@mattvb91 sadly I don't have made any progress, and haven't got the time to investigate other options.

**Comment by benjie** [comment]
I also attempted to fix it in https://github.com/graphile/starter/pull/222 but no luck. Can anyone reproduce this outside of GitHub actions?

**Comment by benjie** [comment]
I've reproduced it locally! To do so was quite simple in the end:

```
NODE_ENV=test yarn build
NODE_ENV=test yarn server start &
NODE_ENV=test yarn worker start &
yarn e2e run run --browser chrome
```

Turns out we can't even load the browser in this circumstance either; the issue seems to be Next.js related rather than Cypress related! :tada:

**Comment by benjie** [comment]
Fixed in [`3afcb19` (#222)](https://github.com/graphile/starter/pull/222/commits/3afcb19d85c399ac1cddca8187ba63f9ead02796)

**Comment by benjie** [comment]
Thanks for your help debugging this everyone! Turned out to be `next build` not working quite right in `NODE_ENV=test`

**Pull request closed without merging**
