### PR TITLE
chore(deps): upgrade most dependencies

### PR DESCRIPTION
**Pull request by benjie**
## Description

Everything except Apollo Client, which needs a bit more work.

## Performance impact

Unknown.

## Security impact

Unknown.

---

Fixes #224 
Fixes #223
Fixes #221

### CODE REVIEW

**Comment by jackbravo** [comment]
This PR seems to need the changes proposed on #221

**Comment by benjie** [comment]
Currently crashing with out of memory issue:

```
  Running:  homepage.spec.ts                                                                (1 of 7)


  HomePage

<--- Last few GCs --->

[8484:0x7f800000000]   781661 ms: Scavenge 1671.7 (2062.5) -> 1665.8 (2063.5) MB, 4.1 / 0.0 ms  (average mu = 0.291, current mu = 0.274) allocation failure 
[8484:0x7f800000000]   781743 ms: Scavenge 1672.9 (2063.5) -> 1667.0 (2064.2) MB, 4.5 / 0.0 ms  (average mu = 0.291, current mu = 0.274) allocation failure 
[8484:0x7f800000000]   781831 ms: Scavenge 1673.8 (2064.2) -> 1668.0 (2065.0) MB, 4.9 / 0.0 ms  (average mu = 0.291, current mu = 0.274) allocation failure 


<--- JS stacktrace --->

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

on.cypress.io/renderer-process-crashed
```

**Comment by benjie** [comment]
Though this now passes CI, it doesn't work in dev thanks to some JS errors in the console and `data-next-hide-fouc` blocking the page.

**Comment by benjie** [comment]
Fixed :+1:

**Pull request merged**
